-- simple read 3
OPTIONAL MATCH (n:Account{id:12})<-[e:transfer]-(m:Account)
WHERE
    e.amount > 30.0
    AND e.timestamp > 10
    AND e.timestamp < 70
    AND m.isBlocked=true
RETURN count(m) * 1.0 as numM
NEXT
OPTIONAL MATCH (n:Account{id:12})<-[e:transfer]-(m:Account)
RETURN count(m) as numIn, numM
NEXT
RETURN CASE WHEN numIn = 0 THEN -1 ELSE round(numM / numIn * 1000) / 1000 END as blockRatio