-- simple read 5
MATCH (n:Account{id:12})<-[e:transfer]-(m:Account)
WHERE
    e.amount > 0
    AND e.timestamp > 0
    AND e.timestamp < 100
RETURN
    m.id as srcId,
    count(e) as numEdges,
    sum(e.amount) as sumAmount
NEXT
RETURN
    srcId,
    numEdges,
    round(sumAmount * 1000) / 1000 as sumAmount
ORDER BY sumAmount DESC, srcId ASC